### ISSUE TITLE
Feature Request: Added Moja Global Poster in Readme 

### ISSUE THREAD

**Issue by Ayush7614** [moja-global/moja_global_docs#103]
### Is your feature request related to a problem? Please describe.

After the Moja global documentation we have added the moja global poster that looks good 

### Describe the solution you'd like.

![image](https://user-images.githubusercontent.com/67006255/133879244-d2b956de-afc4-45e2-953f-387675a75aee.png)
After the Moja global documentation we have added the moja global poster that looks good

**Comment by HarshCasper** [comment]
It is not on priority. We already have the same on the organization README. This adds no value in my opinion.

Please feel free to make another issue on the core contribution part.
