### ISSUE TITLE
Documentation📄: Improve the `CONTRIBUTING.md` for the project

### ISSUE THREAD

**Issue by HarshCasper** [moja-global/moja_global_docs#104]
### What is the current documentation state?

Currently, the existing `CONTRIBUTING.md` leads here: https://github.com/moja-global/About_moja_global/blob/master/CONTRIBUTING.md

We need to have a new `CONTRIBUTING.md` that takes some of the contexts from the existing contributing docs and makes it specific around the areas that we are looking to have contributions for. 

### Why do you want to improve the statement?

The `CONTRIBUTING.md` can be improved by:

- Listing the steps to set up the documentation website locally.
- Adding new documentation, modules and section.
- Adding instructions to make an issue to report bugs/feature requests.
- Adding instructions to make a Pull Request to add new documentation or fix bugs.
- Other areas of contribution (Docs review, maintenance, user experience strategy)

**Comment by shraddhavp** [comment]
@HarshCasper  would like to start  contributing  to moja global with this PR can you please assign this Issue to me ?
