### ISSUE TITLE
Feature Request: Add LightHouse Benchmarks for the website

### ISSUE THREAD

**Issue by HarshCasper** [moja-global/moja_global_docs#108]
### Is your feature request related to a problem? Please describe.

Currently, we are not tracking the performance of the documentation website. We can use automated benchmarking using LightHouse to achieve the same. It can allow us to generate clean HTML and JSON logs to keep track of the performance including other factors, like accessibility, best practices, SEO and more.

### Describe the solution you'd like.

We can add a simple directory called `benchmarks` and a BASH script: 

```sh
#!/bin/bash
if [ ${PWD##*/} != "benchmark" ]
then
    	cd benchmark
fi
npx lighthouse https://docs.moja.global --output json --output HTML
```

Whenever it is run, we can generate the HTML and JSON which can be reviewed to understand the changes happening on the documentation website. The next step will be to add this over a GitHub Actions CI where we can run the workflow on a corn every fortnight and the HTML and JSON can be reviewed by uploading them as an artifact.

**Comment by falguni-k** [comment]
I would like to work on this. Please assign this to me

**Comment by HarshCasper** [comment]
Thanks for taking it up @falguni-k :rocket: 

Please let me know if you need any help :hugs:
