### ISSUE TITLE
Documentation📄: Create a new section `Understanding FLINT`

### ISSUE THREAD

**Issue by HarshCasper** [moja-global/moja_global_docs#109]
### What is the current documentation state?

Currently, all of the FLINT-specific documentation is hosted on the FLINT Wiki which is not accessible for most users. We would like to ideally migrate all of the FLINT specific docs to this documentation site, which should not clash with the development and contributing docs.

### Where is this stated?

https://github.com/moja-global/FLINT/wiki/1.-Moja-FLINT

### Why do you want to improve the statement?

The first step towards this would be to create a new section named `Understanding FLINT`. This should have some basic information about FLINT here: https://github.com/moja-global/FLINT/wiki/1.-Moja-FLINT

Once we have this ready, we can start migrating the rest of the content to these version-controlled docs for better accessibility which would further reflect on our official docs.

**Comment by shraddhavp** [comment]
@HarshCasper  would like to work on this issue

**Comment by Ruchip16** [comment]
@HarshCasper should I take up this issue?
