### ISSUE TITLE
Documentation📄: Add more projects to the FAQ section

### ISSUE THREAD

**Issue by HarshCasper** [moja-global/moja_global_docs#115]
### What is the current documentation state?

Currently, the FAQ majorly talks about:

- FLINT
- GCBM
- FLINT Pro

We have been working on new projects, like FLINT-UI, FLINT Reporting, Taswira. You can find them on our GitHub organization and we would like to have some context about them as well.

### Where is this stated?

https://docs.moja.global/en/latest/faq.html

### Why do you want to improve the statement?

We would ideally like to have: 

- Basic context for the project
- Respective Slack channel for these projects
- Contribution scope for each of these projects

**Comment by AnirudhPanda** [comment]
I can do this @HarshCasper

**Comment by AnirudhPanda** [comment]
Is there any particular order shall I follow here @HarshCasper
