### ISSUE TITLE
Documentation📄: Updating readme regarding python installation

### ISSUE THREAD

**Issue by ShaDe2312** [moja-global/moja_global_docs#117]
### What is the current documentation state?

The readme assumes that you have Python & Pip installed on your local machine.
![image](https://user-images.githubusercontent.com/86540850/135703765-7ff3eb17-5b92-4f5a-82cc-6667790d8529.png)

 

### Where is this stated?

README.md 

### Why do you want to improve the statement?

I think it might be a problem as virtualenv & pip are python commands and a beginner dev might confuse them for windows/linux commands.

### Proposed Statement

Adding a statement about needing to install python to do this, along with a hyperlink to the python website might help

**Comment by ShaDe2312** [comment]
PS: I'd like to be assigned this

**Comment by HarshCasper** [comment]
Good catch! This should be a one-line addition.

**Comment by Sin-Sumit** [comment]
Hey, @HarshCasper I'd like to work on this? Please assign me.

**Comment by ShaDe2312** [comment]
There's a PR solving this issue already, though there are other issues that are up for grabs
