### ISSUE TITLE
Documentation📄: Add links to project documentation

### ISSUE THREAD

**Issue by aornugent** [moja-global/moja_global_docs#148]
### What is the current documentation state?

We have the following project pages:

Project | Documentation Website
-- | --
FLINT UI | https://docs.moja.global/projects/flint-ui/en/latest/
GCBM Chile Data Preprocessing | https://docs.moja.global/projects/GCBM-Chile-Data-Preprocessing-Tools/en/latest/
FLINT Reporting | https://docs.moja.global/projects/flint-reporting/en/latest/

However these are not accessible from the docs.moja.global homepage

### Why do you want to improve the statement?

Add this table to the docs.moja.global landing page and/or the navbar.

**Comment by ishitakeshawani** [comment]
I want to solve this issue.
