### ISSUE TITLE
Small fix in code of conduct 

### ISSUE THREAD

**Issue by chicken-biryani** [moja-global/moja_global_docs#165]
The code of conduct is hosted over

https://docs.moja.global/en/latest/contributing/coc.html and https://community.moja.global/community/code-of-conduct

To do: Change the email under enforcement section from guy@moja.global to mentorship@moja.global across both versions.

**Comment by aniketh-varma** [comment]
Hi @chicken-biryani, I would like to work on this issue.

**Comment by chicken-biryani** [comment]
Hey, @aniketh-varma go ahead!

**Comment by aniketh-varma** [comment]
Hi, @chicken-biryani I was a bit busy, and could not work on the issue. Sorry for the delay, I will make a PR very soon.
