### ISSUE TITLE
Documentation📄: Restructuring documentation structure

### ISSUE THREAD

**Issue by Namyalg** [moja-global/moja_global_docs#183]
### What is the current documentation state?

The contents of the existing documentation are very verbose. It is challenging for new users to navigate through the documentation and further understand how all the components fit together.

### Why do you want to improve the statement?

I want to solve the above-stated problem to enhance the readability and navigation of the main technical documentation

### Proposed Statement

I propose to restructure the documentation as  :

```
 |- Introduction
├── FLINT/
│   ├── Understanding FLINT
│   ├── FLINT Prerequisites
│   └── FLINT Development Setup
├── GCBM // documentation for GCBM added here
│   ├── Understanding GCBM
│   └── GCBM Development Setup
├── Projects/
│   ├── FLINT UI
│   ├── FLINT Reporting
│   ├── FLINT Cloud
│   ├── GCBM Chile Data Preprocessing
│   ├── GCBM Belize
│   └── GCBM Columbia
└── Guidelines/
    ├── Contributions
    ├── FAQ
    └── Style guide 
```

**Comment by chicken-biryani** [comment]
@Namyalg 

While we're at it, do you think we can change the sphinx theme as well?

We'd just have to change one line in conf. py

`html_theme = "sphinx_rtd_theme"`

To: 

html_theme = 'pydata_sphinx_theme'

(After installation ofc...
`pip install pydata-sphinx-theme`)

Or any other theme. The pydata theme is usually used by data science oriented organizations. We can checkout more themes.

What do you think?



cc: @shubhamkarande13 @HarshCasper @aornugent

**Comment by Namyalg** [comment]
Yes, @chicken-biryani , I was looking at https://sphinx-themes.org/ for the options we have
