### ISSUE TITLE
Documentation📄: Extend schema description for all tables in GCBM input_database

### ISSUE THREAD

**Issue by Namyalg** [moja-global/moja_global_docs#187]
### What is the current documentation state?

Currently, the documentation describes the schema for 5 tables out of the 41 tables present in the input_database required to run the GCBM simulation. 
The tables are documented under GCBM Inputs : https://docs.moja.global/en/master/GCBM/GCBMInputs/InvestigatingGCBMInputs/tables.html

### Why do you want to improve the statement?

The schema description for all the tables in the input_database must be added. 
The following file contains the schema description for all the table
[schema.txt](https://github.com/moja-global/moja_global_docs/files/8768106/schema.txt)

**Comment by Crystalsage** [comment]
This seems outstanding. Can I work on this?

**Comment by Namyalg** [comment]
Yes, you can work on it
