### ISSUE TITLE
Developer Workflow/Moja Global GitHub workflow best practices

### ISSUE THREAD

**Issue by Patamap** [moja-global/moja_global_docs#4]
Purpose to add this subcontopic below, 
1. How to make a new GitHub repository
-  Repository creation
- Configure repository
- Set up useful labels
- Set up continuous integration (CI)
- Set up a testing framework?
2. How to maintain a GitHub repository. Refer to https://docs.google.com/document/d/1Yxyu9rfrRc94s3e3lhKFjmcOnudsqrs-fqxYsSJ9QAc/edit#heading=h.oiyve2t0iwuz
- Update issue and pull request data? 
- Adding labels to issues. 
- Updating project boards (refer https://docs.google.com/document/d/1zw-d7v917N4mezckCN0YBBUR4KuiSumqHpHW_YTKD98/edit) 
- Making pull requests
   - Follow contributing guidelines
   - Write useful commit messages. 
- Reviewing pull requests
   - Triage new pull requests
   -  Use continuous integration (CI)

@Tlazypanda @gmajan

**Comment by Tlazypanda** [comment]
Hey @Patamap thanks for the wonderful breakdown :tada: 
Just noting here what's in-progress for now with links 

- Reviewing pull requests https://moja-global-documentation.readthedocs.io/en/latest/DeveloperWorkflow/reviewing.html
- Making pull request https://moja-global-documentation.readthedocs.io/en/latest/DevelopmentSetup/git_and_github_guide.html
- Code contribution best practices (contains writing useful commit messages) https://moja-global-documentation.readthedocs.io/en/latest/contributing/code_contribution_best_practices.html
