### ISSUE TITLE
Remove reference to GSoD from README

### ISSUE THREAD

**Issue by aornugent** [moja-global/moja_global_docs#45]
Now that our docs site is live (thanks @Tlazypanda!) we should change the README, removing the references to GSoD. Instead it should describe the instructions to deploy, configure and contribute to moja global documentation.

**Comment by HarshCasper** [comment]
I am working on this 😄

**Comment by chicken-biryani** [comment]
@HarshCasper ,
I think this issue can be closed as well.

As PR #73 - Removes outdated information, GSoD references in the ReadMe.

**Comment by HarshCasper** [comment]
> @HarshCasper ,
> I think this issue can be closed as well.
> 
> As PR #73 - Removes outdated information, GSoD references in the ReadMe.

Done.
