### ISSUE TITLE
Hunting and fixing Dead Links

### ISSUE THREAD

**Issue by HarshCasper** [moja-global/moja_global_docs#49]
**Describe the bug**

Right now the Documentation Site has a lot of dead links that redirect to nowhere. They mostly show the message `404 Not Found` which can create a bad impression for first-time contributors, looking to get started with the project.

**Expected behavior**

They should redirect to an appropriate page on the documentation site or to an appropriate resource. 

**Additional context**

Here are all the dead links: 

| Dead URL  | Linked Page |
| ------------- | ------------- |
| https://docs.moja.global/en/latest/DevelopmentSetup/git_and_github_guide  | https://docs.moja.global/en/latest/prerequisites/git.html  |
| https://docs.moja.global/en/latest/DevelopmentSetup/contributing/index  | https://docs.moja.global/en/latest/DevelopmentSetup/git_and_github_guide.html  |
| https://docs.moja.global/en/latest/GCBMDevelopmentSetup/prerequisites/python_3.7.html | https://docs.moja.global/en/latest/GCBMDevelopmentSetup/windows_installation.html |
| https://docs.moja.global/en/latest/GCBMDevelopmentSetup/prerequisites/microsoft_access_database_driver.html | https://docs.moja.global/en/latest/GCBMDevelopmentSetup/windows_installation.html | 
| https://docs.moja.global/en/latest/GCBMDevelopmentSetup/prerequisites/visual_c++_redistributable_packages.html | https://docs.moja.global/en/latest/GCBMDevelopmentSetup/windows_installation.html | 
| https://docs.moja.global/en/master/GCBMDevelopmentSetup/prerequisites/python_3.7.html | https://docs.moja.global/en/master/GCBMDevelopmentSetup/windows_installation.html |
| https://docs.moja.global/en/master/GCBMDevelopmentSetup/prerequisites/microsoft_access_database_driver.html | https://docs.moja.global/en/master/GCBMDevelopmentSetup/windows_installation.html |
| https://docs.moja.global/en/master/GCBMDevelopmentSetup/prerequisites/visual_c++_redistributable_packages.html | https://docs.moja.global/en/master/GCBMDevelopmentSetup/windows_installation.html |
| https://docs.moja.global/en/add_instructions_gdal/DevelopmentSetup/contributing/index | https://docs.moja.global/en/add_instructions_gdal/DevelopmentSetup/git_and_github_guide.html |
| https://docs.moja.global/en/add_instructions_gdal/DevelopmentSetup/git_and_github_guide | https://docs.moja.global/en/add_instructions_gdal/prerequisites/git.html |
| https://docs.moja.global/en/add_instructions_gdal/GCBMDevelopmentSetup/prerequisites/python_3.7.html | https://docs.moja.global/en/add_instructions_gdal/GCBMDevelopmentSetup/windows_installation.html | 
| https://docs.moja.global/en/add_instructions_gdal/GCBMDevelopmentSetup/prerequisites/microsoft_access_database_driver.html | https://docs.moja.global/en/add_instructions_gdal/GCBMDevelopmentSetup/windows_installation.html | 
| https://docs.moja.global/en/add_instructions_gdal/GCBMDevelopmentSetup/prerequisites/visual_c++_redistributable_packages.html | https://docs.moja.global/en/add_instructions_gdal/GCBMDevelopmentSetup/windows_installation.html | 
| https://docs.moja.global/en/master/DevelopmentSetup/git_and_github_guide | https://docs.moja.global/en/master/prerequisites/git.html |

We can follow the below strategy to solve this: 

- Take up a chunk of dead links and if we can find the apt page, add the link for the same. If not, then direct the link to some noteworthy resource as an alternative. 
- Contributors can take up batches of these dead link and raise PR for them easily, which would make it fast to remove all of them up.

**Comment by HarshCasper** [comment]
Hi @aornugent @gmajan @Tlazypanda @shubhamkarande13 👋 

Can you please have a look at the same ?

**Comment by chicken-biryani** [comment]
Hey, Can I work on this?

**Comment by shubhamkarande13** [comment]
Fixed and merged with @chicken-biryani 's PR #53.
