### ISSUE TITLE
Improve the flow and details of the documentation.

### ISSUE THREAD

**Issue by chicken-biryani** [moja-global/moja_global_docs#61]
_Edit_

## **To do:**

1) Create a flow diagram of the steps shown in the videos:
 - [FLINT Core on Visual Studio 2019](https://www.youtube.com/watch?v=BmHltWrxCTY) 
 - [FLINT Example (RothC model) on Visual Studio](https://www.youtube.com/watch?v=Jfi2-vEhfkg&t=4s)
 - [FLINT Example (Chapman Richards model) on Visual Studio](https://www.youtube.com/watch?v=JFTyeZQbPjI&t=1s)

2) Create a flow diagram of the navigation in the [documentation.](https://docs.moja.global/en/latest/prerequisites/index.html)

3) Put the diagrams in a zip file, drive and put the link in the comment over here

_(PS: Take this opportunity to set FLINT up on your system.)_

## **Describe what you are trying to do and why it is not optimal.**
While having a discussion with @sarahhaggarty and @shubhamkarande13 we saw that the flow and detailing of the documentation can be improved. As the videos lead to a smooth setup of FLINT and FLINT examples we can use the details of the video to enhance the document.

## **Outcome:**

- Use this issue to further improve the navigation of the [documentation](https://docs.moja.global/en/latest/prerequisites/index.html)
- Set up FLINT in a newcomer's system.

**Comment by shubhamkarande13** [comment]
You may like to try out [Lucidchart]( https://www.lucidchart.com/pages/). 😄

**Comment by chicken-biryani** [comment]
Hey, @aornugent and @HarshCasper This was something we thought of.
If you think there's a better way of doing the same, do let us know.

**Comment by aornugent** [comment]
Awesome! @waridrox has used a Miro board to develop a content map for the community website, or Mermaid.js is a simple way design flowcharts as code.

Excited to see what you come up with!

**Comment by aornugent** [comment]
Example from community site: https://miro.com/app/board/o9J_lFEkawU=/

**Comment by Ayush7614** [comment]
@chicken-biryani i would like to work on the issue please assign me

**Comment by chicken-biryani** [comment]
Hey, @Ayush7614 !

I am glad to see that you're enthusiastic about contributing to moja global! 😄

However, this is an issue I am currently working on.

A good place to get started would be to work on issues that have been labelled as 'good first issue' or 'for new comers'. 🎯

**Comment by sarahhaggarty** [comment]
Hi @Ayush7614, you could also take a look at #62 or #64 and see if you would like to work on either of those 😎 Let me know!

**Comment by chicken-biryani** [comment]
@botmojaglobal claim

**Comment by chicken-biryani** [comment]
@botmojaglobal claim

**Comment by burpcat** [comment]
Hey @chicken-biryani . I'd like to work on this issue. Gimme a go

**Comment by chicken-biryani** [comment]
@burpcat sure! Go ahead!

If you need any help you can ask us over here or on slack.

Try to keep the discussion as public and transparent as possible, so that everyone is in the loop.

**Comment by chicken-biryani** [comment]
Hello all,

**I am putting the links to the rough drafts for the modifications over here**

@AnirudhPanda  was kind enough to point out what was missing in the documentation.
I took the opportunity to put together a rough draft so that even someone very new can find it easier to understand. 

_These are just for the first point. i.e FLINT Core on visual Studio_

Links:
- [Visual Studio Installation](https://docs.google.com/document/d/1S4Tqkb_LQ43CQcRhJC7SL-xuh1zZ--S7QxbqQQm2cWQ/edit?usp=sharing)
- [CMake](https://docs.google.com/document/d/1cjyw30DbIZo-wdGNLlw-vtblceQ0lsfP5pplLUja_6c/edit?usp=sharing)
- [Setting up the FLINT development environment](https://docs.google.com/document/d/1wcAyRFrrLc_9ur0n1y3a_xFq4z_DGNL14LnSynwYIro/edit?usp=sharing)
- [Building the FLINT](https://docs.google.com/document/d/1CHFsxg_DjVY_IQJDF3Ru3x5yCbDjz9rauMTcfAo1HkQ/edit?usp=sharing)
- There were a few minor changes in the Vcpkg installation part. They've been modified.
