### ISSUE TITLE
Provide recommended directory structure for installation

### ISSUE THREAD

**Issue by sarahhaggarty** [moja-global/moja_global_docs#64]
**What does the current documentation state?**
N/A

**Where is this stated?**
N/A

**Why do you want to improve the statement?**
Currently all commands for windows platforms are given with reference to the following directory structure: `C:\Development\moja-global`. However this is never formally introduced to the reader. It would be very helpful for readers from a non-developer background to read this explanation and set up their directory in the same way so they are more likely to complete installation successfully.

**Proposed statement**
I propose to add a new section in [DevelopmentSetup/windows_installation.rst](https://github.com/moja-global/moja_global_docs/blob/master/docs/DevelopmentSetup/windows_installation.rst) between "Prerequisites" and "Using vcpkg to install required libraries." This new section can introduce the recommended directory structure including a screenshot (ideally).

**Additional info**
There is a Note in "Using cmake to build the project" to notify the reader what path the commands are referring to. The videos also follow the `C:\Development\moja-global` directory structure.

**Comment by chicken-biryani** [comment]
Ah! A lot of the improvements you're making are required!

I am glad that you're taking care of these things!

**Comment by sarahhaggarty** [comment]
After a quick review of the latest Docs, this appears to be resolved.
