### ISSUE TITLE
Remove repeating words from documentation.

### ISSUE THREAD

**Issue by Apoorve73** [moja-global/moja_global_docs#71]
**What does the current documentation state?**
FLINT: the Full Lands INtegration Tool The Full Lands Integration Tool (FLINT) is the flagship software developed by the moja global community.

**Where is this stated?**
Present in the second paragraph, under the heading **Moja Global Documentation**, [here](https://docs.moja.global/en/latest/)

**Why do you want to improve the statement?**
The full form for FLINT is repeating twice.

**Proposed statement**
FLINT: The Full Lands INtegration Tool is the flagship software developed by the moja global community.

**Additional info**
None

**Comment by HarshCasper** [comment]
This issue has already been fixed here: https://github.com/moja-global/moja_global_docs/pull/73
