### ISSUE TITLE
Documentation📄: Full Form of FLINT being repeated

### ISSUE THREAD

**Issue by AnirudhPanda** [moja-global/moja_global_docs#78]
### What is the current documentation state?

![mg1](https://user-images.githubusercontent.com/66218496/130598666-156ace2e-1ed8-41cb-8613-83b6a3bd2977.PNG)

### Why do you want to improve the statement?

The full form of FLINT is repeated twice.

### Proposed Statement

**FLINT** which stands for **F**ull **L**ands **IN**tegration **T**ool

### Additional context.

The proposed statement would look good from UI perspective.

**Comment by AnirudhPanda** [comment]
If this issue is genuine I would like to take it!

**Comment by shubhamkarande13** [comment]
Already fixed by @HarshCasper in #73.
