### ISSUE TITLE
Documentation📄: vcpkg section

### ISSUE THREAD

**Issue by AnirudhPanda** [moja-global/moja_global_docs#89]
### What is the current documentation state?

Addressing an issue I encountered and a suggestion too.

In the https://docs.moja.global/en/latest/prerequisites/vcpkg.html page, unlike the video, it is nowhere mentioned to make a folder named `Development` and inside it `moja global` and then cloning `vcpkg`

As I was following the docs completely it led me to errors like  `Could not find MSBuild version with C++ support. VS2015, VS2017, or VS2019 (with C++) needs to be installed.`

Even though I had everything installed. I went to the tutorial and followed there and everything worked.

### Proposed Statement

I think that if it is written specifically to clone `vcpkg` in C drive and then continuing operations.

Also In the Visual Studio installer part, we can highlight installing **Desktop development with C++ workload** and check if it is ticked or not.

**Comment by chicken-biryani** [comment]
Hey, @AnirudhPanda !

With the help of issue #61 we plan on improving the documentation.

Maybe you and @burpcat can work on #61 together?

**Comment by AnirudhPanda** [comment]
> Hey, @AnirudhPanda !
> 
> With the help of issue #61 we plan on improving the documentation.
> 
> Maybe you and @burpcat can work on #61 together?

Yeah sure!

**Comment by chicken-biryani** [comment]
Awesome!

You both can co-ordinate on slack!

**Comment by burpcat** [comment]
Sure @chicken-biryani .. Happy to work with you @AnirudhPanda !
