### ISSUE TITLE
Feature Request: In the Readme file of this repo only Linux based commands are used

### ISSUE THREAD

**Issue by AnirudhPanda** [moja-global/moja_global_docs#90]
### Is your feature request related to a problem? Please describe.

While following the installation of creating the virtual env of the docs I faced this issue
`'source' is not recognized as an internal or external command,
operable program or batch file.` which is understandable as I am on a Windows system. 

### Describe the solution you'd like.

I solved this issue by running `env\Scripts\activate` as On Windows, virtualenv creates a .bat/.ps1 file, so you should run env\Scripts\activate instead (per the virtualenv [documentation on the activate script](https://virtualenv.pypa.io/en/legacy/userguide.html#activate-script)).

**Comment by shubhamkarande13** [comment]
Hey @AnirudhPanda ,
Thanks for opening this issue. You're right, there are no Windows commands in the readme. Could you fork this repo, add those commands in the readme and open a pull request to fix this issue?

**Comment by AnirudhPanda** [comment]
> Hey @AnirudhPanda ,
> Thanks for opening this issue. You're right, there are no Windows commands in the readme. Could you fork this repo, add those commands in the readme and open a pull request to fix this issue?

Yeah! Will do

Thanks

**Comment by shubhamkarande13** [comment]
@AnirudhPanda great job! 🎉🎊

Thank you for your contributions!
